name: Sync Strava Data

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的Git历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install stravalib python-dotenv requests
          
      - name: Fetch Strava data
        run: |
          python scripts/fetch_strava_data.py \
            --client-id "${{ secrets.STRAVA_CLIENT_ID }}" \
            --client-secret "${{ secrets.STRAVA_CLIENT_SECRET }}" \
            --refresh-token "${{ secrets.STRAVA_REFRESH_TOKEN }}"

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/runs/
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "更新跑步数据 $(date '+%Y-%m-%d %H:%M:%S')" && \
            git push
          )