name: Sync Strava Data

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install stravalib==1.5 python-dotenv requests "pydantic<2.0"
      
      - name: Sync Strava Data
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python scripts/fetch_strava_data.py \
            --client-id "$STRAVA_CLIENT_ID" \
            --client-secret "$STRAVA_CLIENT_SECRET" \
            --refresh-token "$STRAVA_REFRESH_TOKEN"
      
      - name: Commit and Push
        run: |
          git config --global user.name 'Strava Sync Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/runs/
          git commit -m "Update running data" || exit 0
          git push
      
      - name: Trigger Deploy Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy-site
          token: ${{ secrets.GITHUB_TOKEN }}